services:
  prometheus:
    image: docker.io/prom/prometheus:v2.51.2
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./CONFIG/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus_data:/prometheus
    restart: no
    networks:
      - home_server

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
        - home_server

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    devices:
      - /dev/kmsg
    networks:
      - home_server

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    networks:
      - home_server
      - host
    pid: host
    volumes:
      - "/:/host:ro,rslave"
      - "/sys/class/power_supply/BAT0/current_now:/sys/class/power_supply/BAT0/current_now:ro,rslave"

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: no
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "jellyfin_config:/config"
      - "/home/kushl/storage/movies:/data/movies"
    ports:
      - 8096:8096
    networks:
      - home_server

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 56:53/tcp
      - 54:53/udp
      - 81:80
    environment:
      TZ: 'Asia/Kolkata'
      WEBPASSWORD: 1qaz2wsx3edc4rfv
    volumes:
      - './CONFIG/etc-pihole:/etc/pihole'
      - './CONFIG/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: no
    networks:
      - home_server

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: 1000:1000
    ports:
      - 24424:80
    volumes:
      - /home/kushl/storage:/srv
      - "/home/kushl/filebrowser.db:/database.db"
    networks:
      - home_server

  nginx:
    image: nginx:1.25.5
    container_name: nginx
    volumes:
      - "./CONFIG/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/certificates/server.crt:/server.crt:ro"
      - "/certificates/server.key:/server.key:ro"
      - "./CONFIG/passkey.txt:/cert_passkey.txt:ro"
    ports:
      - 11111:11111
      - 11112:11112
      - 11113:11113
      - 11114:11114
    environment:
      - NGINX_HOST=homelab
    depends_on:
      - grafana
      - jellyfin
      - pihole
      - filebrowser
    restart: unless-stopped
    networks:
      - home_server

networks:
  home_server:
  host:

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  jellyfin_config:
    driver: local
  jellyfin_cache:
    driver: local
