global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets:
        - 'prometheus:9090'

  - job_name: 'node_exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 1s
    static_configs:
      - targets: ['cadvisor:8080']
